import type { SettingConfig } from '~~/shared/types/settings'

// 存储提供商的枚举值
export const STORAGE_PROVIDERS = ['local', 's3', 'openlist'] as const
export type StorageProvider = (typeof STORAGE_PROVIDERS)[number]

export const DEFAULT_SETTINGS = [
  // NAMESPACE: system
  {
    namespace: 'system',
    key: 'firstLaunch',
    type: 'boolean',
    value: true,
    defaultValue: true,
    label: 'settings.system.firstLaunch.label',
    description: 'settings.system.firstLaunch.description',
    isReadonly: true,
  },
  // NAMESPACE: app
  {
    namespace: 'app',
    key: 'title',
    type: 'string',
    defaultValue: 'LumaAtlas',
    label: 'settings.app.title.label',
    description: 'settings.app.title.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'slogan',
    type: 'string',
    defaultValue: '',
    label: 'settings.app.slogan.label',
    description: 'settings.app.slogan.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'description',
    type: 'string',
    defaultValue: '',
    label: 'settings.app.description.label',
    description: 'settings.app.description.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'author',
    type: 'string',
    defaultValue: '',
    label: 'settings.app.author.label',
    description: 'settings.app.author.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'avatarUrl',
    type: 'string',
    defaultValue: '',
    label: 'settings.app.avatarUrl.label',
    description: 'settings.app.avatarUrl.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.theme',
    type: 'string',
    defaultValue: 'system',
    enum: ['light', 'dark', 'system'],
    label: 'settings.app.appearance.theme.label',
    description: 'settings.app.appearance.theme.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.style',
    type: 'string',
    defaultValue: 'minimal',
    enum: ['minimal', 'editorial'],
    label: 'settings.app.appearance.home.style.label',
    description: 'settings.app.appearance.home.style.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.layout',
    type: 'string',
    defaultValue: 'masonry',
    enum: ['masonry', 'grid', 'feed'],
    label: 'settings.app.appearance.home.layout.label',
    description: 'settings.app.appearance.home.layout.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.source',
    type: 'string',
    defaultValue: 'all',
    enum: ['all', 'featured'],
    label: 'settings.app.appearance.home.source.label',
    description: 'settings.app.appearance.home.source.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.imageRatio',
    type: 'string',
    defaultValue: 'natural',
    enum: ['natural', 'square', 'landscape'],
    label: 'settings.app.appearance.home.imageRatio.label',
    description: 'settings.app.appearance.home.imageRatio.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.contentWidth',
    type: 'string',
    defaultValue: 'wide',
    enum: ['contained', 'wide', 'full'],
    label: 'settings.app.appearance.home.contentWidth.label',
    description: 'settings.app.appearance.home.contentWidth.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.density',
    type: 'string',
    defaultValue: 'comfortable',
    enum: ['compact', 'comfortable', 'airy'],
    label: 'settings.app.appearance.home.density.label',
    description: 'settings.app.appearance.home.density.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.galleryGap',
    type: 'number',
    defaultValue: 12,
    label: 'settings.app.appearance.home.galleryGap.label',
    description: 'settings.app.appearance.home.galleryGap.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.maxColumns',
    type: 'number',
    defaultValue: 6,
    label: 'settings.app.appearance.home.maxColumns.label',
    description: 'settings.app.appearance.home.maxColumns.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.showSlogan',
    type: 'boolean',
    defaultValue: true,
    label: 'settings.app.appearance.home.showSlogan.label',
    description: 'settings.app.appearance.home.showSlogan.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.showStats',
    type: 'boolean',
    defaultValue: true,
    label: 'settings.app.appearance.home.showStats.label',
    description: 'settings.app.appearance.home.showStats.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.showGlobeNav',
    type: 'boolean',
    defaultValue: true,
    label: 'settings.app.appearance.home.showGlobeNav.label',
    description: 'settings.app.appearance.home.showGlobeNav.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.showAlbumsNav',
    type: 'boolean',
    defaultValue: true,
    label: 'settings.app.appearance.home.showAlbumsNav.label',
    description: 'settings.app.appearance.home.showAlbumsNav.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'upload.maxFileSize',
    type: 'number',
    defaultValue: 256,
    label: 'settings.app.upload.maxFileSize.label',
    description: 'settings.app.upload.maxFileSize.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'upload.duplicateCheck.enabled',
    type: 'boolean',
    defaultValue: true,
    label: 'settings.system.upload.duplicateCheck.enabled.label',
    description: 'settings.system.upload.duplicateCheck.enabled.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'upload.duplicateCheck.mode',
    type: 'string',
    defaultValue: 'skip',
    enum: ['warn', 'block', 'skip'],
    label: 'settings.system.upload.duplicateCheck.mode.label',
    description: 'settings.system.upload.duplicateCheck.mode.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'webglImageViewerDebug',
    type: 'boolean',
    defaultValue: false,
    label: 'settings.system.webglImageViewerDebug.label',
    description: 'settings.system.webglImageViewerDebug.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'auth.github.enabled',
    type: 'boolean',
    defaultValue: false,
    label: 'settings.system.auth.github.enabled.label',
    description: 'settings.system.auth.github.enabled.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'auth.github.clientId',
    type: 'string',
    defaultValue: '',
    label: 'settings.system.auth.github.clientId.label',
    description: 'settings.system.auth.github.clientId.description',
  },
  {
    namespace: 'system',
    key: 'auth.github.clientSecret',
    type: 'string',
    defaultValue: '',
    label: 'settings.system.auth.github.clientSecret.label',
    description: 'settings.system.auth.github.clientSecret.description',
    isSecret: true,
  },
  // NAMESPACE: privacy
  {
    namespace: 'privacy',
    key: 'upload.autoEraseLocation',
    type: 'boolean',
    defaultValue: false,
    label: 'settings.privacy.upload.autoEraseLocation.label',
    description: 'settings.privacy.upload.autoEraseLocation.description',
    isPublic: true,
  },
  // NAMESPACE: map
  {
    namespace: 'map',
    key: 'provider',
    type: 'string',
    defaultValue: 'maplibre',
    enum: ['mapbox', 'maplibre'],
    label: 'settings.map.provider.label',
    description: 'settings.map.provider.description',
    isPublic: true,
  },
  {
    namespace: 'map',
    key: 'mapbox.token',
    type: 'string',
    defaultValue: '',
    label: 'settings.map.mapbox.token.label',
    description: 'settings.map.mapbox.token.description',
    isPublic: true,
  },
  {
    namespace: 'map',
    key: 'mapbox.style',
    type: 'string',
    defaultValue: '',
    label: 'settings.map.mapbox.style.label',
    description: 'settings.map.mapbox.style.description',
    isPublic: true,
  },
  {
    namespace: 'map',
    key: 'maplibre.token',
    type: 'string',
    defaultValue: '',
    label: 'settings.map.maplibre.token.label',
    description: 'settings.map.maplibre.token.description',
    isPublic: true,
  },
  {
    namespace: 'map',
    key: 'maplibre.style',
    type: 'string',
    defaultValue: '',
    label: 'settings.map.maplibre.style.label',
    description: 'settings.map.maplibre.style.description',
    isPublic: true,
  },
  // NAMESPACE: location
  {
    namespace: 'location',
    key: 'language',
    type: 'string',
    defaultValue: 'en',
    enum: ['en', 'zh-CN', 'zh-TW', 'ja'] as const,
    label: 'settings.location.language.label',
    description: 'settings.location.language.description',
    isPublic: true,
  },
  {
    namespace: 'location',
    key: 'mapbox.token',
    type: 'string',
    defaultValue: '',
    label: 'settings.location.mapbox.token.label',
    description: 'settings.location.mapbox.token.description',
    isPublic: true,
  },
  {
    namespace: 'location',
    key: 'nominatim.baseUrl',
    type: 'string',
    defaultValue: '',
    label: 'settings.location.nominatim.baseUrl.label',
    description: 'settings.location.nominatim.baseUrl.description',
    isPublic: true,
  },
  // NAMESPACE: storage
  {
    namespace: 'storage',
    key: 'provider',
    type: 'number',
    defaultValue: null,
    label: 'settings.storage_provider.provider.label',
    description: 'settings.storage_provider.provider.description',
  },
] as const satisfies SettingConfig[]

export const settingNamespaces = [
  ...new Set(DEFAULT_SETTINGS.map((s) => s.namespace)),
] as const
export const settingKeys = [
  ...new Set(DEFAULT_SETTINGS.map((s) => s.key)),
] as const

export type SettingNamespace = (typeof settingNamespaces)[number]
export type SettingKey<N extends SettingNamespace> = Extract<
  (typeof DEFAULT_SETTINGS)[number],
  { namespace: N }
>['key']
