import type { SettingConfig } from '~~/shared/types/settings'

// 存储提供商的枚举值
export const STORAGE_PROVIDERS = ['local', 's3', 'openlist'] as const
export type StorageProvider = (typeof STORAGE_PROVIDERS)[number]

export const DEFAULT_SETTINGS = [
  // NAMESPACE: system
  {
    namespace: 'system',
    key: 'firstLaunch',
    type: 'boolean',
    value: true,
    defaultValue: true,
    label: 'settings.system.firstLaunch.label',
    description: 'settings.system.firstLaunch.description',
    isReadonly: true,
  },
  // NAMESPACE: app
  {
    namespace: 'app',
    key: 'title',
    type: 'string',
    defaultValue: 'LumaAtlas',
    label: 'settings.app.title.label',
    description: 'settings.app.title.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'slogan',
    type: 'string',
    defaultValue: '',
    label: 'settings.app.slogan.label',
    description: 'settings.app.slogan.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'description',
    type: 'string',
    defaultValue: '',
    label: 'settings.app.description.label',
    description: 'settings.app.description.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'author',
    type: 'string',
    defaultValue: '',
    label: 'settings.app.author.label',
    description: 'settings.app.author.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'avatarUrl',
    type: 'string',
    defaultValue: '',
    label: 'settings.app.avatarUrl.label',
    description: 'settings.app.avatarUrl.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.theme',
    type: 'string',
    defaultValue: 'system',
    enum: ['light', 'dark', 'system'],
    label: 'settings.app.appearance.theme.label',
    description: 'settings.app.appearance.theme.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.style',
    type: 'string',
    defaultValue: 'minimal',
    enum: ['minimal', 'editorial'],
    label: 'settings.app.appearance.home.style.label',
    description: 'settings.app.appearance.home.style.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.layout',
    type: 'string',
    defaultValue: 'masonry',
    enum: ['masonry', 'grid', 'feed'],
    label: 'settings.app.appearance.home.layout.label',
    description: 'settings.app.appearance.home.layout.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.source',
    type: 'string',
    defaultValue: 'all',
    enum: ['all', 'featured'],
    label: 'settings.app.appearance.home.source.label',
    description: 'settings.app.appearance.home.source.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.imageRatio',
    type: 'string',
    defaultValue: 'natural',
    enum: ['natural', 'square', 'landscape'],
    label: 'settings.app.appearance.home.imageRatio.label',
    description: 'settings.app.appearance.home.imageRatio.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.contentWidth',
    type: 'string',
    defaultValue: 'wide',
    enum: ['contained', 'wide', 'full'],
    label: 'settings.app.appearance.home.contentWidth.label',
    description: 'settings.app.appearance.home.contentWidth.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.density',
    type: 'string',
    defaultValue: 'comfortable',
    enum: ['compact', 'comfortable', 'airy'],
    label: 'settings.app.appearance.home.density.label',
    description: 'settings.app.appearance.home.density.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.galleryGap',
    type: 'number',
    defaultValue: 12,
    label: 'settings.app.appearance.home.galleryGap.label',
    description: 'settings.app.appearance.home.galleryGap.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.maxColumns',
    type: 'number',
    defaultValue: 6,
    label: 'settings.app.appearance.home.maxColumns.label',
    description: 'settings.app.appearance.home.maxColumns.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.showSlogan',
    type: 'boolean',
    defaultValue: true,
    label: 'settings.app.appearance.home.showSlogan.label',
    description: 'settings.app.appearance.home.showSlogan.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.showStats',
    type: 'boolean',
    defaultValue: true,
    label: 'settings.app.appearance.home.showStats.label',
    description: 'settings.app.appearance.home.showStats.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.showExploreNav',
    type: 'boolean',
    defaultValue: true,
    label: 'settings.app.appearance.home.showExploreNav.label',
    description: 'settings.app.appearance.home.showExploreNav.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.showGlobeNav',
    type: 'boolean',
    defaultValue: true,
    label: 'settings.app.appearance.home.showGlobeNav.label',
    description: 'settings.app.appearance.home.showGlobeNav.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.showAlbumsNav',
    type: 'boolean',
    defaultValue: true,
    label: 'settings.app.appearance.home.showAlbumsNav.label',
    description: 'settings.app.appearance.home.showAlbumsNav.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.preset',
    type: 'string',
    defaultValue: 'camlife',
    enum: ['camlife', 'minimal', 'editorial', 'custom'],
    label: 'Homepage preset',
    description: 'The visual preset last applied to the homepage.',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.modules',
    type: 'json',
    defaultValue: {
      order: ['header', 'gallery', 'footer'],
      hidden: [],
    },
    label: 'Homepage modules',
    description: 'Homepage module order and visibility.',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.navigation',
    type: 'json',
    defaultValue: {
      order: ['explore', 'globe', 'albums'],
    },
    label: 'Navigation order',
    description: 'Order of public navigation links.',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.accentColor',
    type: 'string',
    defaultValue: '#171717',
    label: 'Accent color',
    description: 'Accent color used by the public gallery.',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.surfaceStyle',
    type: 'string',
    defaultValue: 'clean',
    enum: ['clean', 'soft', 'contrast'],
    label: 'Surface style',
    description: 'Background and divider treatment for the public gallery.',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.cornerRadius',
    type: 'number',
    defaultValue: 2,
    label: 'Image corner radius',
    description: 'Corner radius used by gallery images.',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.headingFont',
    type: 'string',
    defaultValue: 'wenkai',
    enum: ['sans', 'wenkai', 'serif'],
    label: 'Heading font',
    description: 'Typography used by prominent public headings.',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.socialLinks',
    type: 'json',
    defaultValue: {
      website: '',
      instagram: '',
      x: '',
      github: '',
    },
    label: 'Social links',
    description: 'Links displayed in the public footer.',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.home.footerText',
    type: 'string',
    defaultValue: '',
    label: 'Footer text',
    description: 'Optional custom text displayed in the public footer.',
    isPublic: true,
  },
  // NAMESPACE: publishing
  {
    namespace: 'publishing',
    key: 'rss.enabled',
    type: 'boolean',
    defaultValue: true,
    label: 'settings.publishing.rss.enabled.label',
    description: 'settings.publishing.rss.enabled.description',
    isPublic: true,
  },
  {
    namespace: 'publishing',
    key: 'rss.source',
    type: 'string',
    defaultValue: 'all',
    enum: ['all', 'featured'],
    label: 'settings.publishing.rss.source.label',
    description: 'settings.publishing.rss.source.description',
    isPublic: true,
  },
  {
    namespace: 'publishing',
    key: 'rss.limit',
    type: 'number',
    defaultValue: 20,
    label: 'settings.publishing.rss.limit.label',
    description: 'settings.publishing.rss.limit.description',
    isPublic: true,
  },
  {
    namespace: 'publishing',
    key: 'sharing.enabled',
    type: 'boolean',
    defaultValue: true,
    label: 'settings.publishing.sharing.enabled.label',
    description: 'settings.publishing.sharing.enabled.description',
    isPublic: true,
  },
  {
    namespace: 'publishing',
    key: 'download.originalEnabled',
    type: 'boolean',
    defaultValue: true,
    label: 'settings.publishing.download.originalEnabled.label',
    description: 'settings.publishing.download.originalEnabled.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'upload.maxFileSize',
    type: 'number',
    defaultValue: 256,
    label: 'settings.app.upload.maxFileSize.label',
    description: 'settings.app.upload.maxFileSize.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'upload.duplicateCheck.enabled',
    type: 'boolean',
    defaultValue: true,
    label: 'settings.system.upload.duplicateCheck.enabled.label',
    description: 'settings.system.upload.duplicateCheck.enabled.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'upload.duplicateCheck.mode',
    type: 'string',
    defaultValue: 'skip',
    enum: ['warn', 'block', 'skip'],
    label: 'settings.system.upload.duplicateCheck.mode.label',
    description: 'settings.system.upload.duplicateCheck.mode.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'image.responsive.enabled',
    type: 'boolean',
    defaultValue: true,
    label: 'settings.system.image.responsive.enabled.label',
    description: 'settings.system.image.responsive.enabled.description',
  },
  {
    namespace: 'system',
    key: 'image.responsive.smallWidth',
    type: 'number',
    defaultValue: 480,
    label: 'settings.system.image.responsive.smallWidth.label',
    description: 'settings.system.image.responsive.smallWidth.description',
  },
  {
    namespace: 'system',
    key: 'image.responsive.mediumWidth',
    type: 'number',
    defaultValue: 960,
    label: 'settings.system.image.responsive.mediumWidth.label',
    description: 'settings.system.image.responsive.mediumWidth.description',
  },
  {
    namespace: 'system',
    key: 'image.responsive.largeWidth',
    type: 'number',
    defaultValue: 1600,
    label: 'settings.system.image.responsive.largeWidth.label',
    description: 'settings.system.image.responsive.largeWidth.description',
  },
  {
    namespace: 'system',
    key: 'image.responsive.quality',
    type: 'number',
    defaultValue: 82,
    label: 'settings.system.image.responsive.quality.label',
    description: 'settings.system.image.responsive.quality.description',
  },
  {
    namespace: 'system',
    key: 'webglImageViewerDebug',
    type: 'boolean',
    defaultValue: false,
    label: 'settings.system.webglImageViewerDebug.label',
    description: 'settings.system.webglImageViewerDebug.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'auth.github.enabled',
    type: 'boolean',
    defaultValue: false,
    label: 'settings.system.auth.github.enabled.label',
    description: 'settings.system.auth.github.enabled.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'auth.github.clientId',
    type: 'string',
    defaultValue: '',
    label: 'settings.system.auth.github.clientId.label',
    description: 'settings.system.auth.github.clientId.description',
  },
  {
    namespace: 'system',
    key: 'auth.github.clientSecret',
    type: 'string',
    defaultValue: '',
    label: 'settings.system.auth.github.clientSecret.label',
    description: 'settings.system.auth.github.clientSecret.description',
    isSecret: true,
  },
  // NAMESPACE: privacy
  {
    namespace: 'privacy',
    key: 'upload.autoEraseLocation',
    type: 'boolean',
    defaultValue: false,
    label: 'settings.privacy.upload.autoEraseLocation.label',
    description: 'settings.privacy.upload.autoEraseLocation.description',
    isPublic: true,
  },
  // NAMESPACE: map
  {
    namespace: 'map',
    key: 'provider',
    type: 'string',
    defaultValue: 'maplibre',
    enum: ['mapbox', 'maplibre'],
    label: 'settings.map.provider.label',
    description: 'settings.map.provider.description',
    isPublic: true,
  },
  {
    namespace: 'map',
    key: 'mapbox.token',
    type: 'string',
    defaultValue: '',
    label: 'settings.map.mapbox.token.label',
    description: 'settings.map.mapbox.token.description',
    isPublic: true,
  },
  {
    namespace: 'map',
    key: 'mapbox.style',
    type: 'string',
    defaultValue: '',
    label: 'settings.map.mapbox.style.label',
    description: 'settings.map.mapbox.style.description',
    isPublic: true,
  },
  {
    namespace: 'map',
    key: 'maplibre.token',
    type: 'string',
    defaultValue: '',
    label: 'settings.map.maplibre.token.label',
    description: 'settings.map.maplibre.token.description',
    isPublic: true,
  },
  {
    namespace: 'map',
    key: 'maplibre.style',
    type: 'string',
    defaultValue: '',
    label: 'settings.map.maplibre.style.label',
    description: 'settings.map.maplibre.style.description',
    isPublic: true,
  },
  // NAMESPACE: location
  {
    namespace: 'location',
    key: 'language',
    type: 'string',
    defaultValue: 'en',
    enum: ['en', 'zh-CN', 'zh-TW', 'ja'] as const,
    label: 'settings.location.language.label',
    description: 'settings.location.language.description',
    isPublic: true,
  },
  {
    namespace: 'location',
    key: 'mapbox.token',
    type: 'string',
    defaultValue: '',
    label: 'settings.location.mapbox.token.label',
    description: 'settings.location.mapbox.token.description',
    isPublic: true,
  },
  {
    namespace: 'location',
    key: 'nominatim.baseUrl',
    type: 'string',
    defaultValue: '',
    label: 'settings.location.nominatim.baseUrl.label',
    description: 'settings.location.nominatim.baseUrl.description',
    isPublic: true,
  },
  // NAMESPACE: storage
  {
    namespace: 'storage',
    key: 'provider',
    type: 'number',
    defaultValue: null,
    label: 'settings.storage_provider.provider.label',
    description: 'settings.storage_provider.provider.description',
  },
] as const satisfies SettingConfig[]

export const settingNamespaces = [
  ...new Set(DEFAULT_SETTINGS.map((s) => s.namespace)),
] as const
export const settingKeys = [
  ...new Set(DEFAULT_SETTINGS.map((s) => s.key)),
] as const

export type SettingNamespace = (typeof settingNamespaces)[number]
export type SettingKey<N extends SettingNamespace> = Extract<
  (typeof DEFAULT_SETTINGS)[number],
  { namespace: N }
>['key']
