packages:
  - .
  - packages/*

peerDependencyRules:
  ignoreMissing:
    - '@nuxt/kit'

overrides:
  sharp: 0.34.5

allowBuilds:
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  better-sqlite3: true
  esbuild: false
  sharp: true
  unrs-resolver: false
  vue-demi: false
